### ISSUE TITLE
!default alignment

### ISSUE THREAD

**Issue by entozoon** [adrianlee44/atom-aligner-scss#1]
Love the plugin, and this isn't a bug as such, but is there a way to configure it such that it can align by other characters, such as an exclamation mark? For example, in sass, it's quite typical to initialise variables to be overridable using a default flag. 

```
$tabs-bg:        red !default;
$tabs-color:     dodgerblue !default;
$tabs-font-size: 16px !default;
```

Which, to my eyes, is much more skim-readable in the format:

```
$tabs-bg:        red        !default;
$tabs-color:     dodgerblue !default;
$tabs-font-size: 16px       !default;
```

**Comment by adrianlee44** [comment]
Added support for `!` but aligner currently doesn't support aligning multiple operators in one line. I'll look into adding support for that but for now you'll have to disable aligning `:`.
